fiche/urls.py
from django.contrib import admin
from django.urls import path

from fiche.views import *

app_name = 'main'

urlpatterns = [
    path('', Fiche, name='fiche'),
    path('sources', Sources, name='sources'),
    path('diagramme', Diagramme, name='diagramme'),
    path('approfondissement', Approfondissement, name='approfondissement'),
]

seminaireHeg/urls.py
from django.contrib import admin
from django.urls import path, include

from fiche.views import Diagramme

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', Diagramme, name='main'),
    path('fiche/', include('fiche.urls', namespace='fiche')),
]

fiche/models.py
from django.db import models

# Create your models here.

fiche/views.py
from django.shortcuts import render


def Fiche(request):
    return render(request,'main.html')

def Sources(request):
    return render(request,'sources.html')

def Diagramme(request):
    return render(request,'diagramme.html')

def Approfondissement(request):
    return render(request,'approfondissement.html')

fiche/templates/approfondissement.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.3/js/bootstrap.min.js"></script>
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
    <link rel="stylesheet" href="{% static 'css/main.css' %}" >
    <link rel="icon" href="{% static 'img/icon.png' %}">
    <meta charset="UTF-8">

    <title>Sources</title>
</head>
<body>

<div id="wrapper" class="">

      <!-- Sidebar -->
            <!-- Sidebar -->
      <div id="sidebar-wrapper">
      <ul id="sidebar_menu" class="sidebar-nav">
           <li class="sidebar-brand"><a id="menu-toggle" href="#">Menu<span id="main_icon" class="glyphicon glyphicon-align-justify"></span></a></li>
      </ul>
        <ul class="sidebar-nav" id="sidebar">
            <li><a href="{% url 'main:diagramme' %}">Diagramme<span class="sub_icon glyphicon glyphicon-link"></span></a></li>
            <li><a href="{% url 'main:fiche' %}">Fiche<span class="sub_icon glyphicon glyphicon-link"></span></a></li>
            <li><a href="{% url 'main:sources' %}">Sources/Outils<span class="sub_icon glyphicon glyphicon-link"></span></a></li>
        </ul>
      </div>


<article>
    <div class="container">
        <div class="row">
            <div class ="col-sm-1"></div>
            <div class ="col-sm-10">
                <br />
                <br />
                <h1><b>A remplir</b></h1>

                </div>
        </div>
    </div>
</article>



</div>

</body>
</html>
<script>
$("#menu-toggle").click(function(e) {
        e.preventDefault();
        $("#wrapper").toggleClass("active");
});


</script>

fiche/templates/diagramme.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.3/js/bootstrap.min.js"></script>
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <link rel="stylesheet" href="{% static 'css/main.css' %}" >
    <link rel="icon" href="{% static 'img/icon.png' %}">

    <meta charset="UTF-8">

    <title>Diagramme</title>
</head>
<body>

<div id="wrapper" class="">

      <!-- Sidebar -->
            <!-- Sidebar -->
      <div id="sidebar-wrapper">
      <ul id="sidebar_menu" class="sidebar-nav">
           <li class="sidebar-brand"><a id="menu-toggle" href="#">Menu<span id="main_icon" class="glyphicon glyphicon-align-justify"></span></a></li>
      </ul>
        <ul class="sidebar-nav" id="sidebar">
            <li><a href="{% url 'main:diagramme' %}">Diagramme<span class="sub_icon glyphicon glyphicon-link"></span></a></li>
            <li><a href="{% url 'main:fiche' %}">Fiche<span class="sub_icon glyphicon glyphicon-link"></span></a></li>
            <li><a href="{% url 'main:sources' %}">Sources/Outils<span class="sub_icon glyphicon glyphicon-link"></span></a></li>
        </ul>
      </div>


<article>
    <div class="container">
        <div class="row">
            <div class ="col-sm-1"></div>
            <div class ="col-sm-10"></div>
                <br />
                <br />
                <h1 class="text-center"><b>Diagramme de Venn</b></h1>
                <br />
                <img id="myImg" src="{% static 'img/vulgarisation_diagramme.jpg' %}" alt="Trolltunga, Norway" width="960" height="720">

                <!-- The Modal -->
                <div id="myModal" class="modal">
                  <img class="modal-content" id="img01">
                </div>
        </div>
    </div>
</article>
</div>


</body>


</html>
<script>
$("#menu-toggle").click(function(e) {
        e.preventDefault();
        $("#wrapper").toggleClass("active");
});

// Get the modal
var modal = document.getElementById('myModal');

// Get the image and insert it inside the modal - use its "alt" text as a caption
var img = document.getElementById('myImg');
var modalImg = document.getElementById("img01");
var captionText = document.getElementById("caption");
img.onclick = function(){
    modal.style.display = "block";
    modalImg.src = this.src;
    modalImg.alt = this.alt;
    captionText.innerHTML = this.alt;
}


// When the user clicks on <span> (x), close the modal
modal.onclick = function() {
    img01.className += " out";
    setTimeout(function() {
       modal.style.display = "none";
       img01.className = "modal-content";
     }, 400);

 }

</script>

fiche/templates/main.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.3/js/bootstrap.min.js"></script>
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
    <link rel="stylesheet" href="{% static 'css/main.css' %}" >
    <link rel="icon" href="{% static 'img/icon.png' %}">

    <meta charset="UTF-8">

    <title>Fiche</title>
</head>
<body>

<div id="wrapper" class="">

      <!-- Sidebar -->
            <!-- Sidebar -->
      <div id="sidebar-wrapper">
      <ul id="sidebar_menu" class="sidebar-nav">
           <li class="sidebar-brand"><a id="menu-toggle" href="#">Menu<span id="main_icon" class="glyphicon glyphicon-align-justify"></span></a></li>
      </ul>
        <ul class="sidebar-nav" id="sidebar">
            <li><a href="{% url 'main:diagramme' %}">Diagramme<span class="sub_icon glyphicon glyphicon-link"></span></a></li>
            <li><a href="{% url 'main:fiche' %}">Fiche<span class="sub_icon glyphicon glyphicon-link"></span></a></li>
            <li><a href="{% url 'main:sources' %}">Sources/Outils<span class="sub_icon glyphicon glyphicon-link"></span></a></li>
        </ul>
      </div>


<article>
    <div class="container">
        <div class="row">
            <div class ="col-sm-1"></div>
            <div class ="col-sm-10">
                <br />
                <br />
                <h1><b>Diffusion, communication, vulgarisation</b></h1>
                <br/>
                <!--
                <h2><b>Définition des termes</b></h2>

                <h3><b>Diffusion</b></h3>

                <p class="text-justify">La diffusion se définit par la communication de l’information et peut prendre plusieurs formes. Adaptée au profil du récepteur et de ses besoins, comme toute communication concernant les informations issues de la veille, celle-ci doit faire l’objet d’une politique déterminée à l’avance. La diffusion de l’information demande d’être pensée, tout comme chaque étape du cycle de la veille (objectifs, collecte, analyse…).</p>

                <h3><b>Communication</b></h3>

                <p>Processus de transmission d’informations d’un émetteur vers un récepteur. "La communication doit recommander ce qui est possible ; elle doit rester réaliste par rapport au service effectivement rendu (bien que les différents auteurs s’accordent sur cette recommandation, il est difficile d’y voir une spécificité de la communication des services ; en effet, la même recommandation doit être formulée pour le marketing des produits, qu’il s’agisse de grande consommation ou de business to business)..."(Jean-Marc Decaudin et Denis Lacoste).</p>

                <h3><b>Vulgarisation</b></h3>

                <p>Action de mettre à la portée du plus grand nombre, des non-spécialistes des connaissances techniques et scientifiques.</p>

                <h2><b>Questions</b></h2>
                -->
                <h3><b>Comment vulgariser un propos scientifique sans perdre en qualité ?</b></h3>

                <p><mark>Le propos scientifique peut poser des problèmes de compréhension au grand public, car il s’adresse à des spécialistes. Il faut donc le <a href="https://www.cnrtl.fr/definition/vulgariser">vulgariser</a> afin de le rendre compréhensible au public non-averti. Or, en vulgarisant un propos, on risque de perdre en qualité. Pour ce faire, il faut :</mark></p>

                <blockquote>
                    <p>1. <b>Assimiler</b> (c’est-à-dire : comprendre le contenu de l’article) : le lire plusieurs fois,
                    prendre des notes, en discuter en groupe</p>
                </blockquote>
                <blockquote>
                    <p>2. <b>Trier</b> quelles informations il faut retenir et lesquelles sont superflues : résumer l’article en 5 mots (qui parlent au public-cible), dégager les grands axes, s’assurer qu’on transmet ce qui est essentiel, en mettant de côté ce qui est trop précis ou superflu pour ce qu’on souhaite expliquer. Attention : on s’attachera à rester neutre autant que possible, à prioriser l’honnêteté intellectuelle, afin de rester fidèle à la démarche scientifique de départ.</p>
                </blockquote>
                <blockquote>
                    <p>3. <b>Synthétiser</b>, bien penser au temps qu’on a à disposition – on ne dit pas la même chose si on a 30 minutes ou si on a 1 heure. Le niveau de détail de l’explication de l’article scientifique dépendra aussi du cadre temporel qui nous est donné. Privilégier les phrases courtes par exemple.</p>
                </blockquote>
                <blockquote>
                    <p>4. <b>Traduire, adapter</b> le propos au public-cible : faire attention au vocabulaire, si du jargon est utilisé, penser à le définir d’abord, être bien structuré et s’assurer que le propos est cohérent. </p>
                </blockquote>

                <h3><b>Quels sont les outils de communication et de diffusion efficaces dans notre domaine ?</b></h3>

                <p><mark>Les outils de communication sont des supports qui facilitent la <a href="https://www.cnrtl.fr/definition/diffusion">diffusion</a> d’informations entre un émetteur et un public cible. Il s’agit de les connaître et de les exploiter de façon adéquate, afin de parvenir à l’objectif fixé : faire connaître l’existence du séminaire aux publics potentiellement intéressés, et faire comprendre le propos scientifique vulgarisé au public présent.</mark></p>


                <p><b>Avant le séminaire</b> : faire connaître le séminaire au public-cible. Dans le milieu professionnel, les outils les plus utilisés sont souvent l’emailing, les newsletters, les blogs, les réseaux sociaux.</p>

                <blockquote>
                    <p>1.  Listes de diffusion : mailings (swiss-lib, liste des étudiants, intranet… )</p>
                </blockquote>
                <blockquote>
                    <p>2. Blogs : Recherches d’Idées, d’autres blogs à trouver éventuellement:</p>
                    <ul>
                        <li><p>2.1 Recherches d’Idées - <a href="https://campus.hesge.ch/blog-master-is/">lien</a></p></li>
                        <li><p>2.2 Bibliothèque de Genève - <a href="https://blog.bge-geneve.ch/2020/09/ ">lien</a></p></li>
                        <li><p>2.3 Synopsis, veille stratégique de l’UNIL - <a href=" https://uniris.unil.ch/synopsis/perimetre-veille/">lien</a></p></li>
                        <li><p>2.4 Biblioblogueur et formateur - <a href="https://jpaccart.blog.tdg.ch/">lien</a></p></li>
                    </ul>
                </blockquote>
                <blockquote>
                    <p>3. Présentations orales (dans les séminaires de Bachelor ID)</p>
                </blockquote>
                <blockquote>
                    <p>4. Réseaux sociaux:</p>
                    <ul>
                        <li><p>4.1 Twitter : Compte @heg_id ; liste « Info-Doc » de 100 membres répertorié <a href="https://twitter.com/i/lists/1244991734775451650">lien</a></p></li>
                        <li><p>4.2 Facebook</p></li>
                        <li><p>4.3 LinkedIn (sur les pages et groupes spécialisés)</p></li>
                    </ul>
                </blockquote>
                <blockquote>
                    <p>5. Site web de la Haute école de gestion et agenda de la HES-SO</p>
                </blockquote>
                <blockquote>
                    <p>6. Réseau d’alumni</p>
                </blockquote>

                <p><b>Durant le séminaire</b> :</p>

                <blockquote>
                    <p>7. Être conscient de ce qu’on dégage dans l’attitude, dans le non-verbal : parler et se positionner clairement, être dynamique et positif.</p>
                </blockquote>
                <blockquote>
                    <p>8. Penser à la répartition de la parole entre intervenants : elle doit être cohérente.</p>
                </blockquote>
                <blockquote>
                    <p>9. Faire participer le public, favoriser les interactions : poser des questions, utiliser des outils comme les clickers, les sondages sur Zoom, les quiz, les jeux.</p>
                </blockquote>

                <h3><b>Comment intéresser un public externe aux thématiques des séminaires ?</b></h3>
                <p><mark>Pour une bonne vulgarisation, il faut d’abord <b>connaître son public</b>. La bonne question à se poser est : « à qui m’adresse-je ? »,
                    afin d’avoir une idée de ce que connaît le public visé (connaissances scientifiques) et de ses attentes (à chaque public, son style de vulgarisation et de communication).
                    Ainsi, on pourra préparer au mieux <b>le propos et la forme</b> du séminaire afin qu’ils <b>soient adaptés au public présent.</b></mark></p>
                <blockquote>
                    <p> 1. Identifier les <b>différents types de public</b> potentiels :</p>
                    <ul>
                        <li><p>1.1 professeurs, assistants, doctorants.</p></li>
                        <li><p>1.2 étudiants BA.</p></li>
                        <li><p>1.3 professionnels : médiateurs culturels, bibliothécaires, archiviste, chef de projet.</p></li>
                    </ul>
                </blockquote>
                <blockquote>
                    <p>2. <b>Trouver ce qui peut intéresser</b> ces différents types de public afin de répondre au mieux aux attentes, questions et exigences qu’ils pourraient avoir.</p>
                </blockquote>
                <blockquote>
                    <p>3. Ne pas oublier les <b>échanges avec le public</b> (interactions) : prévoir un temps d’échange, de question, de débat à la fin de la présentation ?</p>
                </blockquote>


                <h3><b>Quel intérêt d’ouvrir les séminaires au public externe ?</b></h3>

                <blockquote>
                    <p> 1. Faire connaître nos travaux, aborder des problématiques actuelles.</p>
                </blockquote>
                <blockquote>
                    <p> 2. Echanges : avoir des retours, critiques, points de vue divers et variés, nous remettre
                        en question (accepter la critique)</p>
                </blockquote>
                <blockquote>
                    <p>3. Discussion intéressante possible, débat</p>
                </blockquote>
                <blockquote>
                    <p>4. Apprendre à maitriser son sujet, synthétiser, adapter son propos, savoir intéresser</p>
                </blockquote>


                <br />
                <br />
                <br />
                <br />
                <br />
                <br />
<!--
                <p>---------------------------------------------TEST------------------------------------------------------------</p>

                <p> <a href="">Test</a> <mark>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</mark> <i><b> porchetta tail </b></i><strong>drumstick</strong> <s> A alias aperiam distinctio ducimus earum harum itaque iure officia porro saepe sed sit temporibus, voluptatum.</s></p>

                <pre>
                    <code>
 Aspernatur ipsa officiis quo sequi vel!
                    </code>
                </pre>

        -->

            </div>
        </div>
    </div>
</article>



</div>

</body>
</html>
<script>
$("#menu-toggle").click(function(e) {
        e.preventDefault();
        $("#wrapper").toggleClass("active");
});


</script>

fiche/templates/sources.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.3/js/bootstrap.min.js"></script>
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
    <link rel="stylesheet" href="{% static 'css/main.css' %}" >
    <link rel="icon" href="{% static 'img/icon.png' %}">

    <meta charset="UTF-8">

    <title>Sources</title>
</head>
<body>

<div id="wrapper" class="">

      <!-- Sidebar -->
            <!-- Sidebar -->
      <div id="sidebar-wrapper">
      <ul id="sidebar_menu" class="sidebar-nav">
           <li class="sidebar-brand"><a id="menu-toggle" href="#">Menu<span id="main_icon" class="glyphicon glyphicon-align-justify"></span></a></li>
      </ul>
        <ul class="sidebar-nav" id="sidebar">
            <li><a href="{% url 'main:diagramme' %}">Diagramme<span class="sub_icon glyphicon glyphicon-link"></span></a></li>
            <li><a href="{% url 'main:fiche' %}">Fiche<span class="sub_icon glyphicon glyphicon-link"></span></a></li>
            <li><a href="{% url 'main:sources' %}">Sources/Outils<span class="sub_icon glyphicon glyphicon-link"></span></a></li>
        </ul>
      </div>


<article>
    <div class="container">
        <div class="row">
            <div class ="col-sm-1"></div>
            <div class ="col-sm-10">
                <br />
                <br />
                <h1><b>Sources</b></h1>

                <p><a href="https://www.kokoroe.fr/list/competences-humaines/article/outils-de-communication-les-tops-et-les-pieges-1197">https://www.kokoroe.fr/list/competences-humaines/article/outils-de-communication-les-tops-et-les-pieges-1197</a></p>

                <p><a href="https://www.mt180.ch/accueil/">https://www.mt180.ch/accueil/</a></p>

                <p><a href="https://books.openedition.org/pum/7692?lang=fr">https://books.openedition.org/pum/7692?lang=fr</a></p>

                <p>Nicolas Beck, En finir avec les idées reçues sur la vulgarisation scientifique, Versailles, Quae, 2017, 171 p</p>
                <p>Daniel Jacobi, La communication scientifique : discours, figures, modèles, Grenoble France, Presses universitaires de Grenoble, coll. « Communication, médias et sociétés », 1999, 277 p</p>
                <p>Pascal Lapointe, Guide de vulgarisation : au-delà de la découverte scientifique : la sociéte, Québec, Éditions MultiMondes, coll. « Au-delà de la découverte scientifique », 2008, 319 p</p>
                <p>Cécile Michaut, Vulgarisation scientifique, mode d'emploi, EDPSciences, 2014, 160 p</p>
                <p>Dominique Wolton, De la vulgarisation à la communication, CNRS Editions, « Hermès, La Revue », 1997/1, n°21, pp. 9-14</p>

                <h1><b>Outils</b></h1>

                <h3><b>Outils pour les présentations Power Point :</b></h3>

                <p><a href="https://prezi.com">https://prezi.com</a>: outil qui a l’avantage d’être adapté à des applications comme Teams, Zoom, etc.</p>

                <p><a href="https://canva.com">https://canva.com</a>: utile également pour la création de poster, flyers, infographies ou graphiques.</p>

                <p><a href="https://www.haikudeck.com/">https://www.haikudeck.com/</a>: outil qui a l’avantage de proposer une base de données de plusieurs millions d’images libres de droit.</p>

                <p><a href="https://piktochart.com">https://piktochart.com</a>: infographies, posters ou flyersc.</p>

                <h3><b>Outils pour la création de graphiques/tableaux :</b></h3>

                <p><a href="https://www.datawrapper.de/">https://www.datawrapper.de/</a>: outil qui offre la possibilité de créer des graphiques, des cartes et des tableaux.</p>

                <p><a href="https://graphiste.com/blog/outils-gratuits-creer-graphiques">https://graphiste.com/blog/outils-gratuits-creer-graphiques</a>: outil qui offre la possibilité d’importer ses propres données.</p>

                <p><a href="https://public.tableau.com/en-us/s/">https://public.tableau.com/en-us/s/</a>: application téléchargeable et gratuite.</p>

                <p><a href="https://canva.com">https://piktochart.com</a>: outil qui offre la possibilité de créer des graphiques, des cartes et des tableaux</p>


                <h3><b>D’autres outils utiles :</b></h3>

                <p>Banque d’images libres de droit :</p>
                <p><a href="https://pixabay.com/">https://pixabay.com/</a></p>
                <p><a href="https://unsplash.com/">https://unsplash.com/</a></p>
                <p><a href="https://fotomelia.com/">https://fotomelia.com/</a></p>


                <h3><b>Outils pour créer des nuages de mots :</b></h3>

                <p><a href="https://nuagedemots.co/">https://pixabay.com/</a></p>
                <p><a href="https://wordart.com/create">https://wordart.com/create</a></p>

                <br />
                <br />
            </div>
        </div>
    </div>
</article>



</div>

</body>
</html>
<script>
$("#menu-toggle").click(function(e) {
        e.preventDefault();
        $("#wrapper").toggleClass("active");
});


</script>